#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : autoconf213
Version  : 2.13
Release  : 1
URL      : http://mirrors.kernel.org/gnu/autoconf/autoconf-2.13.tar.gz
Source0  : http://mirrors.kernel.org/gnu/autoconf/autoconf-2.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: autoconf213-bin
Requires: autoconf213-data
Requires: autoconf213-doc
Patch1: autoconf213-destdir.patch

%description
Autoconf
Autoconf is an extensible package of m4 macros that produce shell
scripts to automatically configure software source code packages.
These scripts can adapt the packages to many kinds of UNIX-like
systems without manual user intervention.  Autoconf creates a
configuration script for a package from a template file that lists the
operating system features that the package can use, in the form of m4
macro calls.

%package bin
Summary: bin components for the autoconf213 package.
Group: Binaries
Requires: autoconf213-data

%description bin
bin components for the autoconf213 package.


%package data
Summary: data components for the autoconf213 package.
Group: Data

%description data
data components for the autoconf213 package.


%package doc
Summary: doc components for the autoconf213 package.
Group: Documentation

%description doc
doc components for the autoconf213 package.


%prep
%setup -q -n autoconf-2.13
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522173138
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1522173138
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/autoconf
/usr/bin/autoheader
/usr/bin/autoreconf
/usr/bin/autoscan
/usr/bin/autoupdate
/usr/bin/ifnames

%files data
%defattr(-,root,root,-)
/usr/share/autoconf/acconfig.h
/usr/share/autoconf/acfunctions
/usr/share/autoconf/acgeneral.m4
/usr/share/autoconf/acheaders
/usr/share/autoconf/acidentifiers
/usr/share/autoconf/acmakevars
/usr/share/autoconf/acoldnames.m4
/usr/share/autoconf/acprograms
/usr/share/autoconf/acspecific.m4
/usr/share/autoconf/autoconf.m4
/usr/share/autoconf/autoconf.m4f
/usr/share/autoconf/autoheader.m4
/usr/share/autoconf/autoheader.m4f

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
